vrk-kpa/suomifi-design-system

- package.json
- src/pages/styles/colors.tsx
- yarn.lock
- Refactored colors page to handle changed tokens and typings for functions that find what code is invalid
> Update suomifi-ui-components to 0.2.4

- .gitignore
- src/components/Annotation.tsx
- src/components/ContentBoxes.tsx
- src/components/Hero.tsx
- Fixed front page indentation and alignment according to design
- Vscode added to gitignore
> [Bugfix]Fix frontpage indents and alignment

- .tx/config
- locale/af/toggle.json
- locale/en/toggle.json
- locale/fi/toggle.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/toggle.tsx
- Added page for Toggle component.
- Transifex source file added
- Finnish (as translated) & English (dummy) translations file added from the Transifex
> [Feature] Adds Toggle to the site under components

- .tx/config
- locale/af/dropdown.json
- locale/en/dropdown.json
- locale/fi/dropdown.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/dropdown.tsx
Adds page about the dropdown component to the site. Source file and Finnish content translation added to transifex. 
Tested by automated linting and snapshots, as well as running locally.
> [Feature] Add dropdown page

- locale/af/common.json
- locale/en/common.json
- locale/fi/common.json
- src/components/NotificationBox.tsx
Add a notification box component to allow notifications for content pages. Mainly meant for style and component pages where the content is still subject to change.
> [Feature] Add notification component

- .tx/config
- locale/af/text.json
- locale/en/text.json
- locale/fi/text.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/text.tsx
- Added page for Text component 
- Transifex source file and translated Finnish added
- English (dummy) translations file pulled from the Transifex and added to the project
> [Feature] Text component added with descriptions and examples

- locale/af/typography.json
- locale/en/typography.json
- locale/fi/typography.json
- src/pages/styles/typography.tsx
Updated Typography page to have updated content shown on the page.
- Now also showing the line height after the heading and text style
- showing the value and unit straight from the design tokens; if those changes no need to manually change some px-values here
- Updated the Transifex translation files
> [Feature] Typography styles update

- .tx/config
- locale/af/textinput.json
- locale/en/textinput.json
- locale/fi/textinput.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/textinput.tsx
Adds a page presenting the textinput element (the element itself is still a work in progress). 
Tested by linting and running locally.
> [Feature] Add textinput page

- .tx/config
- locale/af/searchinput.json
- locale/en/searchinput.json
- locale/fi/searchinput.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/searchinput.tsx
Added a page presenting the search input component. It is subject to change so I only added a single example and the work in progress notification.
Tested by linting and running locally.
> [Feature] Add search input page

- package.json
- yarn.lock
Update `suomifi-ui-components` to version **0.6.1**
> [Feature] Update suomifi-ui-components to 0.6.1

- src/pages/components/icon.tsx
- Adds displayName for Icon and StaticIcon wrappers
- Needs better implementation later on
> Quick fix for icon example code minification bug.

- src/pages/components/button.tsx
- yarn.lock
- Upgrade dependencies, no breaking changes
- Remove one unnecessary console.log
> Upgrade dependencies and remove unnecessary console.log.

- src/pages/components/block.tsx
Since the component in question is still under construction, added the work in progress notification to the top of the page.
Tested by running locally.
> [Enhancement] Add notification box to the top of the block component page

- package.json
- yarn.lock
Update `suomifi-ui-components` to version **0.9.0**
> Update suomifi-ui-components dependency to 0.9.0

- .tx/config
- locale/af/languagemenu.json
- locale/en/languagemenu.json
- locale/fi/languagemenu.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/languagemenu.tsx
Adds a page presenting the language menu component.
Tested by building and running locally.
> [Feature]Add language menu component page

- package.json
Raise version number to 0.1.2 in anticipation of merging to master.
> Release version 0.1.2

- locale/af/designers.json
- locale/en/designers.json
- locale/fi/accessibility.json
- locale/fi/designers.json
- locale/fi/info.json
- Adds missing translation content & structure that was originally implemented in PR #190 but was lost in during [this commit](https://github.com/vrk-kpa/suomifi-design-system/commit/d9d098ee80739c7e35b6e9970ac07d51d32f7e05)
- Also fixed small typo on accessibility page of FI
> [Fix]Adds missing translation content & structure

- yarn.lock
Upgraded the dependencies to dismiss dependbot's PR's regarding those old versions.
Ran`yarn upgrade`
- Tested locally `yarn build`
- Tested locally `yarn develop`
> [Feature] Upgrade the dependencies

- locale/fi/home.json
Added disclaimer text regarding the accessibility.
> [Feature] Added the disclaimer text for accessibility

- locale/en/common.json
- locale/fi/common.json
- locale/fi/home.json
Getting ready for 1.0 release and therefore the **alpha** texts will be changed to **beta**.
> [Feature] Change alpha-texts to beta

- locale/af/toggle.json
- locale/en/toggle.json
- locale/fi/toggle.json
- src/pages/components/toggle.tsx
- Added the input-variation of Toggle to be also showcased
- Added new section to describe the situation when to use one of these two types of Toggle
> [Feature] Input-variation of Toggle added

- package.json
- yarn.lock
Update `suomifi-ui-components` to 0.16.1
Updating the `suomifi-ui-components` to it's latest version before merging `develop` to `master`.
> [Feature] Update suomifi-ui-components to 0.16.1

- src/pages/components/dropdown.tsx
Add WIP notification for the Dropdown component as it will have breaking changes incoming at the moment.
> [Feature] Add WIP notification for Dropdown

- locale/af/dropdown.json
- locale/en/dropdown.json
- locale/fi/dropdown.json
- package.json
- src/pages/components/dropdown.tsx
- yarn.lock
This PR updates the suomifi-ui-components dependency to 0.17.0. The new version brings changes and new features to the Dropdown component, so the component page content and examples are adjusted to accommodate the changes and present new features.
Tested by running locally.
> [Improvement] Update ui-components to 0.17.0 and add new Dropdown page content

- package.json
- yarn.lock
Update the suomifi dependencies to latest versions
> [Update] Update suomifi dependencies to 1.0

- package.json
- yarn.lock
- Update `suomifi-ui-components` to latest **v1.0.1**
> [Update] suomifi-ui-components to latest v1.0.1

- package.json
- yarn.lock
Release the site presenting the fix introduced in the **1.0.1** release of `suomifi-ui-components`.
> [Release] Using suomifi-ui-components v1.0.1

- yarn.lock
- Upgrade all dependencies according to their scope.
- Fix related security issues.
> [Feature] Upgrade all dependencies according to scope.

- package.json
- Textarea component
- RadioButton component
- Upgrade dependencies
> [Release] 0.2.0

- package.json
- src/components/ExampleComponents.tsx
- src/components/Heading.tsx
- src/config/sidenav/components.js
- src/pages/components/expander.tsx
- src/pages/components/heading.tsx
- src/pages/components/multiselect.tsx
- src/pages/styles/typography.tsx
- yarn.lock
* Update to use suomifi-ui-components v4.0.0-beta.7
* Renamed / removed props for **Expander** and it's components
* Heading component because of the complications caused by adding the support for `ref` (both the site wide used and the one that is demonstrated)
* MultiSelect prop renaming changes
To be able to have MultiSelect and Expander testable in the accessibility clinic with the help of DS-site.
> [Feature] Update to use suomifi-ui-components v4.0.0-beta.7

- .tx/config
- locale/af/modal.json
- locale/af/multiselect.json
- locale/en/modal.json
- locale/en/multiselect.json
- locale/fi/modal.json
- locale/fi/multiselect.json
- package.json
- src/config/sidenav/components.js
- src/pages/components/modal.tsx
- src/pages/components/multiselect.tsx
- yarn.lock
* Update to use suomifi-ui-components v4.0.0-beta.8
* Add Dialog (Modal) component page
> [Feature] Modal page

- .tx/config
- locale/fi/singleselect.json
- package.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/singleselect.tsx
- yarn.lock
> [Feature] Single Select component page

- .tx/config
- locale/af/alert.json
- locale/en/alert.json
- locale/fi/alert.json
- package.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/alert.tsx
- yarn.lock
> [Feature] Alert component page

- locale/af/notification.json
- locale/en/notification.json
- locale/fi/notification.json
- package.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/notification.tsx
- yarn.lock
This PR adds the Notification component page to the site. It contains the relevant menu additions as well as locale entries. It also updates `suomifi-ui-components` dependency to 6.2.0, which contains the Notification component.
> [Feature] Notification component page

- locale/af/toast.json
- locale/en/toast.json
- locale/fi/toast.json
- package.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/toast.tsx
- storage/.verdaccio-db.json
- yarn.lock
- Update to use suomifi-ui-components v6.2.0-beta.2
- Add Toast component page
> [Feature] Toast to DS-site

- locale/af/tooltip.json
- locale/en/tooltip.json
- locale/fi/tooltip.json
- package.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/tooltip.tsx
- yarn.lock
- Update to use suomifi-ui-components v9.0.0-beta.0
- Add Tooltip component page
> [Feature] Tooltip

- locale/af/loadingspinner.json
- locale/en/loadingspinner.json
- locale/fi/loadingspinner.json
- Updates LoadingSpinner time description to a bit "softer" tone.
- Add missing localisation files
> Update LoadingSpinner time description

- package.json
- yarn.lock
This PR updates the `suomifi-ui-components` dependency to its latest stable version 9.0.0
> [Update] suomifi-ui-components version 9.0.0

- locale/fi/servicenavigation.json
- locale/fi/sidenavigation.json
- locale/fi/wizardnavigation.json
- package.json
- src/components/MainContent.tsx
- src/config/sidenav/components.js
- src/pages/components/servicenavigation.tsx
- src/pages/components/sidenavigation.tsx
- src/pages/components/wizardnavigation.tsx
- yarn.lock
* Add pages for `<ServiceNavigation>`, `<WizardNavigation>` and `<SideNavigation>`
* Update `suomifi-ui-components` to 9.1.0-beta.3
* Increase SideNav width from 22rem to 23rem to prevent the longest component names from going to two lines
> [Feature] Navigation components

- locale/fi/servicenavigation.json
- locale/fi/sidenavigation.json
- src/pages/components/sidenavigation.tsx
This PR contains the following changes:
- SideNav: Remove aria-current="location" attributes
- SideNav: Adjust accessibility instructions
- ServiceNav: Adjust accessibility instructions
> [Fix] Update ServiceNav & SideNav texts

- next.config.js
PR adds missing basePath variable.
> Add base path to nextjs config

- package.json
- yarn.lock
Update suomifi-ui-components and suomifi-design-tokens dependencies.
> Update suomifi-ui-components and suomifi-design-tokens

- next.config.js
- pages/_document.tsx
PR fixes 
- a link issue with AWS S3 hosting
- Flash Of Unstyled Text (FOUT) issue which stemmed from styled-components
> [Fix] Hosting & styled components rendering fixes

- components/ComponentExample/ComponentCode.tsx
- components/Header/MobileNavMenuButton/MobileNavMenuButton.tsx
- i18n/translations.fi.json
- package.json
- pages/components/dropdown.tsx
- pages/components/textinput.tsx
- yarn.lock
This PR
- updates Dropdown and TextInput examples to display actual use cases
- updates suomifi-ui-components to version 10.0.1
- fixes component examples to not always display scrollbar
- fixes mobile menu to close when user navigates to a page
> [Feature/Fix] Update examples

- .gitignore
- i18n/translations.fi.json
- package.json
- pages/components/actionmenu.tsx
- pages/components/button.tsx
- pages/components/languagemenu.tsx
- styles/globals.scss
- utils/components-sidenav.ts
- utils/icons.tsx
- yarn.lock
- Add a page for `<ActionMenu>`
- Update `<Button>` page
- Update `<LanguageMenu>` page
- Update `suomifi-icons` to  7.0.1
- Update `suomifi-ui-components` to 12.0.0
> [Feature] ActionMenu

- components/StaticForm/StaticForm.tsx
- i18n/translations.fi.json
- package-lock.json
- package.json
- pages/components/errorsummary.tsx
- pages/components/multiselect.tsx
- pages/components/singleselect.tsx
- pages/patterns/static-form.tsx
- utils/components-sidenav.ts
- utils/patterns-sidenav.ts
PR adds a page for static form validation pattern as well as a simple page for the ErrorSummary component separately
> [Feature] Static form validation pattern & ErrorSummary

- i18n/translations.fi.json
- package-lock.json
- package.json
- pages/components/details.tsx
- utils/components-sidenav.ts
This PR will add a documentation page for the `<Details>` component. It also updates `suomifi-ui-components` dependency to the latest beta version.
> [Feature] Details component page

- i18n/translations.fi.json
- pages/components/fileinput.tsx
- utils/components-sidenav.ts
This PR adds a documentation page for the `<FileInput>` component
> [Feature] FileInput page

- package-lock.json
- package.json
PR updates `suomifi-ui-components` to version 15.0.0
> Update suomifi-ui-components to 15.0.0

- i18n/translations.fi.json
- pages/_app.tsx
- pages/components/chip.tsx
- utils/components-sidenav.ts
PR adds documentation page for the `<Chip>` (and `<StaticChip>`) component
> [Feature] Chip 
