- package.json
The deleted parts were already included in the pre-push hook.
Contemplated adding a prettier check with a more detailed output, but eventually decided that there's no need since the most relevant information needed is if the changes require "prettier --write" to be ran.
> [Refactor] Run only prettier check on pre-commit hook - closes #71

- .tx/config
- locale/af/accessibility-statement.json
- locale/en/accessibility-statement.json
- locale/fi/accessibility-statement.json
- locale/fi/common.json
- src/pages/accessibility-statement.tsx
This PR adds an accessibility statement for the site and a related link to the site footer.
- Accessibility statement is a new component
- Translations and content are stored in related localisation files
> Add accessibility statement for site

- .tx/config
- locale/af/link.json
- locale/fi/link.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/dropdown.tsx
- src/pages/components/link.tsx
Added a page for the link component under the component section. Proofread, adjusted and added content from the design team. Examples for regular link and external link added. The component itself is still missing some variants, which need to be added to the examples when implemented.
> [Feature] Add link page

- .tx/config
- locale/af/heading.json
- locale/af/link.json
- locale/fi/heading.json
- locale/fi/link.json
- src/components/ExampleComponents.tsx
- src/config/sidenav/components.js
- src/pages/components/heading.tsx
Adds page presenting the heading component as per the design at https://app.goabstract.com/projects/3a1da570-1a2e-11e9-abe1-6b4306612e83/branches/ff7912c2-de11-4839-a857-412219dbddcc/commits/9d1827f30ecfa5dbeffd736e1e1ea3fa4128c6f8/files/C651C602-77CE-48B5-901D-D0AED36B4A0F/layers/886DD421-1C91-4FF5-9ABE-8BAB824989BD?mode=build&selected=921863136-9844BF13-B47C-4419-A246-B6C05135E69F
Also fixed a couple of small typos (missing periods) from the Link page.
Tested by running locally and test hooks.
> [Feature] Add heading page

- src/components/ComponentExample.tsx
- src/pages/components/button.tsx
Adjusted component example background to be white (used to be gray) and added a gray border as per design. This was done by adjusting values in the ComponentExample component. The button page had some custom stylings, which were adjusted to match the new style.
Tested by lint checks and by running locally
> [Bugfix] Set component example background to white

- src/pages/styles/colors.tsx
- src/pages/styles/icons.tsx
Recent addition of borders for component examples made icon and color example look slightly off. Added overriding styles removing the borders.
> [Bugfix] Remove borders from icon and color examples

- .tx/config
Fixed a conflicting name in transifex configuration. Translations hadn't been pushed to transifex yet so it shouldn't have affected anything.
> [Bugfix] Fix name in transifex config file

- locale/fi/toggle.json
Improved the Toggle component's texts
- When toggling the component -> screenreader reads the state
- Example component's label to more describing
> [Feature] Improve the Toggle's texts

- src/components/MainContent.tsx
Skip link to main content doesn't work in reliable way; sometimes it works and sometimes it doesn't.
This is trying to get this working every time.
- main-content to have `tabIndex=-1`
- focus outline set to `none` for the main-content
> To make any target element focusable, add tabindex="-1" to the element. If the target is an a element, adding tabindex="-1" will remove it from the tab order.
Source: https://fae.disability.illinois.edu/rulesets/BYPASS_1/
Australian design system uses similar technic: https://designsystem.gov.au/components/skip-link/
Tested to work on macOS Chrome & Safari
> [Fix] Skip link functionality

- .circleci/config.yml
After the version 0.11.0 of suomifi-ui-components the Gatsby build progress time has increased noticeably.
Based on the [documentation](https://circleci.com/docs/2.0/executor-types/) this change could possible solve the current issue until the root cause for the increase is found and fixed, if possible.
> [Feature] CircleCi to use 'machine' instead of 'docker' as executor

- locale/af/textarea.json
- locale/en/textarea.json
- locale/fi/textarea.json
- src/pages/components/textarea.tsx
- src/pages/components/textinput.tsx
Textarea and Text Input content keys were accidentally mixed. This PR fixes them. In addition, a placeholder was added to Textarea error example for consistency.
> [Fix] Textarea and textinput content keys

- locale/af/textinput.json
- locale/en/textinput.json
- locale/fi/textinput.json
- package.json
- src/pages/components/textinput.tsx
- yarn.lock
This PR adjusts the text input component page to reflect the recent changes in the component. Removed the WIP notification and added some content and a new example.
Content approved by designers and matched with that in confluence. Not pushed to transifex yet.
> [Feature] Text input page update

- package.json
Increase version to 1.0.0 as the design system is no longer considered to be in beta.
As discussed elsewhere, this repository is not published to NPM and there are no external stakeholders who would be interested in the version. Because of that, versioning should reflect internal changes and major version should communicate a larger rework of either content or code.
> [Release] 1.0.0

- src/components/ExampleComponentUtil.tsx
- src/components/ExampleComponents.tsx
- src/pages/components/button.tsx
- src/pages/components/checkbox.tsx
- src/pages/components/dropdown.tsx
- src/pages/components/expander.tsx
- src/pages/components/heading.tsx
- src/pages/components/modal.tsx
- src/pages/components/multiselect.tsx
- src/pages/components/radiobutton.tsx
- src/pages/components/textarea.tsx
- src/pages/components/textinput.tsx
- src/pages/components/toggle.tsx
- src/pages/styles/typography.tsx
- yarn.lock
Refactor example components abstraction to remove redundant code from component code examples. This change reintroduces the example components abstraction for all components to apply displayName. This is needed to allow using components across the site for code example without duplicating displayName logic.
Some issues with Modal code examples are also fixed with this PR.
Additionally, caniuse-lite is upgraded.
> Refactor Example components abstraction to reduce duplication.

- README.md
Fix the links in the README.
No longer having the language in url-path as we are not using i18n solution anymore.
> Fix links in README; remove language from url-path

- locale/af/alert.json
- locale/en/alert.json
- locale/fi/alert.json
This PR adds instructions that were discussed in the recent accessibility clinic to the Alert component page. The instructions are related to the accessible use of InlineAlert in cases where the alert is connected to a certain interactive element on the page.
> [Fix] InlineAlert usage instructions for Alert component page

- src/config/sidenav/components.js
Toast link was two times in navigation. This PR removes another.
> [Fix] Toast, removed Extra link from navigation

- src/pages/components/tooltip.tsx
Tooltip example was showing weird tags for the `Heading` and `Text` components used in the example.
Problem was caused because example used the components from wrong place therefore missing the required `displayName`.
When running in dev mode, `yarn develop`, the problem does not exist.
You have to run in prod mode, `yarn build` & `yarn start` to see the problem without this fix, in e.g `develop` branch.
Then run in the same way with this branch to see that it should be fixed.
Before the fix:
> [Fix] Tooltip example showed weird tags

- locale/fi/wizardnavigation.json
- src/pages/components/wizardnavigation.tsx
This PR changes `<WizardNavigation>` examples so that the elements which are currently disabled are still in the tab order, so screen reader users can know they exist. 
Also added some texts to reflect the feedback received from the accessibility clinic.
> [Fix]: WizardNav: Adjust examples based on accessibility clinic feedback

- i18n/translations.fi.json
PR removes reference to the confirmation feature, that was removed from DateInput.
> DateInput: Remove reference to deleted confirm button in DateInput

- components/ComponentExample/ComponentExample.tsx
- i18n/translations.fi.json
- pages/components/index.tsx
- pages/styles/index.tsx
- pages/styles/spacing.tsx
PR removes code examples (Expanders) from component pages. Hopefully this directs users more towards Styleguidist. 
Examples are still shown on other pages (like main styles & components pages) because it makes sense there. 
This is done by adding a prop called `showCode` to `<ComponentExample>`. Prop defaults to false
> [Feature] Remove code examples from component pages

- .circleci/config.yml
PR adds sudo to `npm install` command to CircleCI pipeline so that the command won't run into permission issues
> [FIx] Run npm install with sudo in CircleCI
